//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MVC5RealWorld.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chore
    {
        public int ChoreID { get; set; }
        public string AssignedTo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> BronzeValue { get; set; }
        public Nullable<int> SilverValue { get; set; }
        public Nullable<int> GoldValue { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string MaturityLevel { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<bool> NeedExtension { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> RequestedExtensionDeadline { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
    }
}
